USE_STM32 = 1
USE_MSPM0 = 0


SECTOR_SIZE = (0x400)

if USE_MSPM0:
# FLASH
    FLASH_START_ADDR = (0x00000000)
    FLASH_SIZE = (16*1024)
    FLASH_END_ADDR = (FLASH_START_ADDR + FLASH_SIZE)

    FLASH_BLD_START = (FLASH_START_ADDR)
    FLASH_BLD_SIZE = (6*1024)

    FLASH_APP_START = (FLASH_START_ADDR + FLASH_BLD_SIZE)
    FLASH_APP_SIZE = (8*1024)

    FLASH_SYSTEM_INFO_START = (FLASH_APP_START +FLASH_APP_SIZE)
    FLASH_SYSTEM_INFO_SIZE = (SECTOR_SIZE)

    FLASH_IMAGE_INFO_START = (FLASH_SYSTEM_INFO_START + FLASH_SYSTEM_INFO_SIZE)
    FLASH_IMAGE_INFO_SIZE = (SECTOR_SIZE)

    FLASH_IMAGE_INFO_END = (FLASH_IMAGE_INFO_START + FLASH_IMAGE_INFO_SIZE)
    
    # RAM
    RAM_START_ADDR = (0x20000000)
    RAM_SIZE = (0x00000400)
    RAM_END_ADDR = (RAM_START_ADDR + RAM_SIZE)
elif USE_STM32:
    FLASH_START_ADDR = (0x08000000)
    FLASH_SIZE = (64*1024)
    FLASH_END_ADDR = (FLASH_START_ADDR + FLASH_SIZE)

    FLASH_BLD_START = (FLASH_START_ADDR)
    FLASH_BLD_SIZE = (16*1024)

    FLASH_APP_START = (FLASH_START_ADDR + FLASH_BLD_SIZE)
    FLASH_APP_SIZE = (46*1024)

    FLASH_SYSTEM_INFO_START = (FLASH_APP_START +FLASH_APP_SIZE)
    FLASH_SYSTEM_INFO_SIZE = (SECTOR_SIZE)

    FLASH_IMAGE_INFO_START = (FLASH_SYSTEM_INFO_START + FLASH_SYSTEM_INFO_SIZE)
    FLASH_IMAGE_INFO_SIZE = (SECTOR_SIZE)

    FLASH_IMAGE_INFO_END = (FLASH_IMAGE_INFO_START + FLASH_IMAGE_INFO_SIZE)
    
    # RAM
    RAM_START_ADDR = (0x20000000)
    RAM_SIZE = (0x00005000)
    RAM_END_ADDR = (RAM_START_ADDR + RAM_SIZE)
    


# check validation
if FLASH_IMAGE_INFO_END > FLASH_END_ADDR:
    print("Flash image overflow. Please check again!")
elif FLASH_IMAGE_INFO_END < FLASH_END_ADDR:
    print("Define total flash size is smaller than default. Please check again!")



