#ifndef MEMORY_MAP_H
#define MEMORY_MAP_H

#define MAIN_APP_SIZE (0x2000)
#define SECTOR_SIZE (0x400)



// FLASH
#define FLASH_START_ADDR (0x00000000)
#define FLASH_SIZE (16*1024)
#define FLASH_END_ADDR (FLASH_START_ADDR + FLASH_SIZE)

#define FLASH_BLD_START (FLASH_START_ADDR)
#define FLASH_BLD_SIZE (6*1024)

#define FLASH_APP_START (FLASH_START_ADDR + FLASH_BLD_SIZE)
#define FLASH_APP_SIZE (8*1024)

#define FLASH_MAIN_APP_ADDR (FLASH_APP_START)

#define FLASH_SYSTEM_INFO_START (FLASH_APP_START +FLASH_APP_SIZE)
#define FLASH_SYSTEM_INFO_SIZE (SECTOR_SIZE)

#define FLASH_IMAGE_INFO_START (FLASH_SYSTEM_INFO_START + FLASH_SYSTEM_INFO_SIZE)
#define FLASH_IMAGE_INFO_SIZE (SECTOR_SIZE)

#define FLASH_IMAGE_INFO_END (FLASH_IMAGE_INFO_START + FLASH_IMAGE_INFO_SIZE)
#if FLASH_IMAGE_INFO_END > FLASH_END_ADDR
#error "Flash image overflow. Please check again!"
#elif FLASH_IMAGE_INFO_END < FLASH_END_ADDR
#error "Define total flash size is smaller than default. Please check again!"
#endif

//RAM
#define RAM_START_ADDR (0x20000000)
#define RAM_SIZE (0x00000400)
#define RAM_END_ADDR (RAM_START_ADDR + RAM_SIZE)




#endif